# Generated by Django 4.0 on 2023-09-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Название курса')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Описание курса')),
                ('start_date', models.DateField(verbose_name='Старт курса')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('count_lessons', models.PositiveIntegerField(verbose_name='Кол-во уроков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.user', verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название урока')),
                ('preview', models.TextField(max_length=100, verbose_name='Описание урока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=None, verbose_name='Курс пройден')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user', verbose_name='Ученик')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
    ]
