# Generated by Django 4.0 on 2023-10-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'permissions': (('modify_course', 'Can modify course content'),), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course'], 'permissions': (('modify_lesson', 'Can modify lesson content'),), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
