# Generated by Django 4.0 on 2023-10-30 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(db_table='course_authors', related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='АвторЫ курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(help_text='В формате дд.мм.гггг, а теги НЕ РАБОТАЮТ', verbose_name='Старт курса'),
        ),
    ]
