# Generated by Django 4.0 on 2023-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='NotUsed'),
        ),
    ]
